#!/usr/bin/env bash
set -euo pipefail

# Refresh the Cloudflare real IP allow list used by nginx.
# Usage: ./scripts/update-cloudflare-real-ip.sh [output_path]

TARGET_FILE="${1:-/opt/services/whenparty/infra/nginx/conf.d/cloudflare_real_ip.conf}"
COMPOSE_DIR="${COMPOSE_DIR:-/opt/services/whenparty/infra}"
NGINX_SERVICE="${NGINX_SERVICE:-nginx}"

TMP_FILE="$(mktemp)"
trap 'rm -f "$TMP_FILE"' EXIT

timestamp="$(date -u +"%Y-%m-%dT%H:%M:%SZ")"

{
  echo "# Generated by update-cloudflare-real-ip.sh"
  echo "# Source: https://www.cloudflare.com/ips/"
  echo "# Generated at: $timestamp"
  echo ""
} >"$TMP_FILE"

fetch_ips() {
  local family="$1"
  local url="https://www.cloudflare.com/ips-$family"

  if ! data="$(curl -fsSL "$url")"; then
    echo "Failed to download $url" >&2
    exit 1
  fi

  echo "# Cloudflare IPv$family ranges" >>"$TMP_FILE"
  while IFS= read -r cidr; do
    [ -z "$cidr" ] && continue
    echo "set_real_ip_from $cidr;" >>"$TMP_FILE"
  done <<<"$data"
  echo "" >>"$TMP_FILE"
}

fetch_ips 4
fetch_ips 6

changed=1
if [ -f "$TARGET_FILE" ] && cmp -s "$TMP_FILE" "$TARGET_FILE"; then
  echo "Cloudflare IP list unchanged."
  changed=0
else
  install -D -m 0644 "$TMP_FILE" "$TARGET_FILE"
  echo "Updated $TARGET_FILE"
fi

if ! command -v docker >/dev/null 2>&1; then
  echo "docker not available; skipping nginx reload." >&2
  exit 0
fi

if [ ! -d "$COMPOSE_DIR" ]; then
  echo "Compose directory $COMPOSE_DIR not found; skipping nginx reload." >&2
  exit 0
fi

pushd "$COMPOSE_DIR" >/dev/null

if ! docker compose ps "$NGINX_SERVICE" >/dev/null 2>&1; then
  echo "nginx service '$NGINX_SERVICE' not found in docker compose; skipping reload." >&2
  popd >/dev/null
  exit 0
fi

if [ "$changed" -eq 1 ] && docker compose ps --status running "$NGINX_SERVICE" >/dev/null 2>&1; then
  docker compose exec "$NGINX_SERVICE" nginx -t
  docker compose exec "$NGINX_SERVICE" nginx -s reload
  echo "Reloaded nginx after updating allow list."
elif [ "$changed" -eq 1 ]; then
  echo "nginx service '$NGINX_SERVICE' is not running; updated allow list but did not reload." >&2
fi

popd >/dev/null
